import {
  AlertTriangle,
  Anchor,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  Box,
  Building2,
  Check,
  CircleDollarSign,
  CloudFog,
  Disc3,
  Droplets,
  Factory,
  FileBarChart,
  Flame,
  Gauge,
  Globe,
  Grid2x2,
  Grid3x3,
  Hammer,
  Handshake,
  HardHat,
  HeartPulse,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  MapPin,
  Mountain,
  Package,
  Phone,
  TrendingUp,
  Recycle,
  Recycle as RecycleIcon,
  Scale,
  Shield,
  Sprout,
  Square,
  TrainFront,
  Trees,
  Triangle,
  Truck,
  Users,
  Warehouse,
  Wrench,
  Wind,
  Zap,
} from 'lucide-react';

const MAP = {
  recycle: Recycle,
  layers: Layers,
  sparkles: Zap,
  package: Package,
  coil: Disc3,
  wrench: Wrench,
  bars: Grid2x2,
  angle: Triangle,
  square: Square,
  sheet: Layers,
  grid: Grid3x3,
  gate: Scale,
  stairs: TrendingUp,
  shield: Shield,
  shed: Warehouse,
  factory: Factory,
  wind: Wind,
  droplets: Droplets,
  mountain: Mountain,
  leaf: Leaf,
  globe: Globe,
  alert: AlertTriangle,
  trash: RecycleIcon,
  trees: Trees,
  users: Users,
  trending: TrendingUp,
  chart: BarChart3,
  check: Check,
  phone: Phone,
  pin: MapPin,
  handshake: Handshake,
  truck: Truck,
  lightbulb: Lightbulb,
  gauge: Gauge,
  heart: HeartPulse,
  flame: Flame,
  cloud: CloudFog,
  box: Box,
  building: Building2,
  hardhat: HardHat,
  landmark: Landmark,
  anchor: Anchor,
  sprout: Sprout,
  badge: BadgeCheck,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  file: FileBarChart,
  train: TrainFront,
  dollar: CircleDollarSign,
};

export function uiIcon(name) {
  if (!name) return null;
  const key = String(name).toLowerCase().trim();
  return MAP[key] || null;
}

export const allIconNames = Object.keys(MAP);